---
# Source: airflow/templates/secrets/api-secret-key-secret.yaml
############################################
## Airflow Api Flask Secret Key Secret
############################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-api-secret-key
  labels:
    tier: airflow
    component: api-server
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
type: Opaque
data:
  api-secret-key: "VDlFbXUwUVV3aGpscjdhcXIxTDlWdnh0UU1rTUNNeFQ="
