---
# Source: airflow/templates/secrets/fernetkey-secret.yaml
################################
## Airflow Fernet Key Secret
#################################
# Fernet key value must be b64enc
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  labels:
    tier: airflow
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  fernet-key: "ZWpRME1XbFBNME01WkRaaGFHMU1XR2xZYlVwWk1HMHhVMHR3U2xwM1VYUT0="
