---
# Source: airflow/templates/secrets/jwt-secret.yaml
############################################
## Airflow JWT Secret
############################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-jwt-secret
  labels:
    tier: airflow
    component: api-server
    release: airflow
    chart: airflow
    heritage: Helm
type: Opaque
data:
  jwt-secret: "M3l2N1NYWndWc2lvSldlRHJqcG9QRVpVMVNSeksxNmI="
