---
# Source: airflow/templates/workers/worker-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  labels:
    tier: airflow
    component: worker
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: worker
    release: airflow
  ports:
    - name: worker-logs
      protocol: TCP
      port: 8793
      targetPort: 8793
---
# Source: airflow/templates/workers/worker-service.yaml
################################
## Airflow Worker Service
#################################
