---
# Source: airflow/templates/dag-processor/dag-processor-serviceaccount.yaml
################################
## Airflow Dag Processor ServiceAccount
#################################
  
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "airflow-dag-processor"
  labels:
    tier: airflow
    component: dag-processor
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
