---
# Source: airflow/templates/api-server/api-server-service.yaml
################################
## Airflow API Server Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-api-server
  labels:
    tier: airflow
    component: api-server
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: api-server
    release: airflow
  ports:
  
    -
      name: api-server
      port: 8080
