---
# Source: airflow/templates/api-server/api-server-serviceaccount.yaml
######################################
## Airflow API Server ServiceAccount
######################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "airflow-api-server"
  labels:
    tier: airflow
    component: api-server
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
