executor: LocalExecutor

migrateDatabaseJob:
  enabled: true
  useHelmHooks: false

createUserJob:
  useHelmHooks: false
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user

postgresql:
  enabled: true

redis:
  enabled: false

triggerer:
  enabled: false
