---
# Source: airflow/templates/scheduler/scheduler-serviceaccount.yaml
################################
## Airflow Scheduler ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "airflow-scheduler"
  labels:
    tier: airflow
    component: scheduler
    release: airflow
    chart: "airflow-1.19.0"
    heritage: Helm
